# Generated by Django 3.0.7 on 2020-07-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='zero', max_length=50, null=True)),
                ('conferma', models.CharField(blank=True, default='zero', max_length=50, null=True)),
            ],
        ),
    ]
