# Generated by Django 3.0.7 on 2020-07-21 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0030_auto_20200705_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(blank=True, default='False', max_length=10, null=True)),
                ('mesiCaparra', models.IntegerField(blank=True, default='0', null=True)),
                ('citta', models.CharField(max_length=40)),
                ('zona', models.CharField(blank=True, default='none', max_length=40, null=True)),
                ('via', models.CharField(blank=True, default='none', max_length=40, null=True)),
                ('tipo_immobile', models.CharField(blank=True, default='none', max_length=100, null=True)),
                ('piano', models.CharField(blank=True, default='none', max_length=40, null=True)),
                ('m_quadri', models.IntegerField(blank=True, null=True)),
                ('studenti', models.CharField(blank=True, default='none', max_length=10, null=True)),
                ('animali', models.CharField(blank=True, default='none', max_length=40, null=True)),
                ('ascensore', models.CharField(blank=True, default='none', max_length=40, null=True)),
                ('ariaCond', models.CharField(blank=True, default='none', max_length=40, null=True)),
                ('wifi', models.CharField(blank=True, default='none', max_length=40, null=True)),
                ('stanzaDoppia', models.IntegerField(blank=True, default='0', null=True)),
                ('stanzaSingola', models.IntegerField(blank=True, default='0', null=True)),
                ('stanzaTripla', models.IntegerField(blank=True, default='0', null=True)),
                ('postiTotali', models.IntegerField(blank=True, null=True)),
                ('bagni', models.IntegerField(blank=True, default='0', null=True)),
                ('balconi', models.IntegerField(blank=True, default='0', null=True)),
                ('coinquiliniPresenti', models.IntegerField(blank=True, default='0', null=True)),
                ('prezzo', models.IntegerField()),
                ('prezzoCondominio', models.IntegerField(blank=True, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('foto1', models.ImageField(blank=True, default='none', null=True, upload_to='')),
                ('foto2', models.ImageField(blank=True, default='none', null=True, upload_to='')),
                ('foto3', models.ImageField(blank=True, default='none', null=True, upload_to='')),
                ('foto4', models.ImageField(blank=True, default='none', null=True, upload_to='')),
                ('foto5', models.ImageField(blank=True, default='none', null=True, upload_to='')),
                ('foto6', models.ImageField(blank=True, default='none', null=True, upload_to='')),
                ('foto7', models.ImageField(blank=True, default='none', null=True, upload_to='')),
                ('foto8', models.ImageField(blank=True, default='none', null=True, upload_to='')),
                ('foto9', models.ImageField(blank=True, default='none', null=True, upload_to='')),
                ('foto10', models.ImageField(blank=True, default='none', null=True, upload_to='')),
                ('foto11', models.ImageField(blank=True, default='none', null=True, upload_to='')),
                ('foto12', models.ImageField(blank=True, default='none', null=True, upload_to='')),
                ('foto13', models.ImageField(blank=True, default='none', null=True, upload_to='')),
                ('foto14', models.ImageField(blank=True, default='none', null=True, upload_to='')),
                ('foto15', models.ImageField(blank=True, default='none', null=True, upload_to='')),
                ('foto16', models.ImageField(blank=True, default='none', null=True, upload_to='')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='accounts.ProfileP')),
                ('thunders', models.ManyToManyField(blank=True, related_name='thunders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Casa',
                'verbose_name_plural': 'Case',
            },
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenuto', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('casa_recensione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Casa')),
                ('utente_recensione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recensione',
                'verbose_name_plural': 'Recensioni',
            },
        ),
    ]
