# Generated by Django 3.0.4 on 2020-05-20 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0009_auto_20200418_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileP',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('agency', models.CharField(blank=True, default=' ', max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='img.jpg', null=True, upload_to='media'),
        ),
    ]
