# Generated by Django 3.0.4 on 2020-05-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200520_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agency',
            field=models.CharField(blank=True, default='no', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profilep',
            name='agency',
            field=models.CharField(blank=True, default='si', max_length=10, null=True),
        ),
    ]
