# Generated by Django 3.0.4 on 2020-05-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200520_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilep',
            name='agency',
            field=models.CharField(blank=True, default='n', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profilep',
            name='mobile',
            field=models.CharField(blank=True, default='n', max_length=50, null=True),
        ),
    ]
