# Generated by Django 3.0.7 on 2020-06-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200522_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'maschio'), ('F', 'femmina')], max_length=10, null=True),
        ),
    ]
