# Generated by Django 2.2.13 on 2020-07-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200618_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='idZoom1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='idZoom2',
            field=models.CharField(blank=True, default='zero', max_length=300, null=True),
        ),
    ]
