# Generated by Django 2.2.13 on 2020-07-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20200705_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='idZoom1',
            field=models.CharField(blank=True, default='zero', max_length=300, null=True),
        ),
    ]
