# Generated by Django 2.2.13 on 2020-10-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20200705_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aboutMe',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='idZoom1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='idZoom2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='link1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='link2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='maxima',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pass1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pass2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
