# Generated by Django 2.2.13 on 2020-10-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_profilestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
