# Generated by Django 2.2.13 on 2020-10-21 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
