# Generated by Django 2.2.13 on 2020-10-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_casa_tv'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='termosifoni',
            field=models.CharField(blank=True, default='si', max_length=40, null=True),
        ),
    ]
