# Generated by Django 2.2.13 on 2020-10-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_casa_termosifoni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casa',
            old_name='termosifoni',
            new_name='lavatrice',
        ),
        migrations.AddField(
            model_name='casa',
            name='riscaldamento',
            field=models.CharField(blank=True, default='si', max_length=40, null=True),
        ),
    ]
