# Generated by Django 3.0.4 on 2020-04-17 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('city', models.CharField(max_length=50, null=True)),
                ('occupation', models.CharField(max_length=50, null=True)),
                ('age', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default='df.jpg', null=True, upload_to='df.jpg')),
                ('aboutMe', models.CharField(blank=True, max_length=500, null=True)),
                ('maxima', models.CharField(blank=True, max_length=50, null=True)),
                ('pet', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
