# Generated by Django 3.0.4 on 2020-04-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200418_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
