# Generated by Django 3.0.4 on 2020-05-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200520_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='agency',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='profilep',
            name='owner',
            field=models.CharField(blank=True, default='si', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profilep',
            name='agency',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
