# Generated by Django 3.0.4 on 2020-05-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200520_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='owner',
            field=models.CharField(blank=True, default='profile', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profilep',
            name='owner',
            field=models.CharField(blank=True, default='profilep', max_length=10, null=True),
        ),
    ]
