# Generated by Django 3.0.4 on 2020-05-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200522_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='img.jpg', null=True, upload_to='media-serve'),
        ),
    ]
