# Generated by Django 3.0.4 on 2020-05-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200522_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile/superman.jpeg', null=True, upload_to='profile'),
        ),
    ]
