# Generated by Django 3.0.7 on 2020-06-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200618_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
