# Generated by Django 3.0.7 on 2020-06-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20200618_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile/superman.jpeg', null=True, upload_to='profile/'),
        ),
    ]
