# Generated by Django 3.0.7 on 2020-09-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoom',
            name='casa',
            field=models.CharField(blank=True, default='home0', max_length=50, null=True),
        ),
    ]
